name: DEV 브랜치 배포하기
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    runs-on: macos-latest
    environment: development
    steps:
      - name: 브랜치 가져오기
        uses: actions/checkout@v2

      - name: Ruby 설정하기
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 애드온 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 시크릿 파일 생성하기
        run: |
          echo "$PLAYSTORE_SA" > play_keyfile.json && \
          echo "$GCP_FASTLANE_SA" > gcp_keyfile.json && \
          echo "$GENERIC_APP_SECRETS" > secrets.properties && \
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json && \
          echo "$APP_SIGNING_SECRET" > ./keystore.b64 && \
          base64 -d -i ./keystore.b64 > ./app/bbibbi_android
        env:
          PLAYSTORE_SA: ${{ secrets.PLAYSTORE_SA }}
          GCP_FASTLANE_SA: ${{ secrets.GCP_FASTLANE_SA }}
          GENERIC_APP_SECRETS: ${{ secrets.GENERIC_APP_SECRETS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          APP_SIGNING_SECRET: ${{ secrets.APP_SIGNING_SECRET }}

      - name: Fastlane 배포하기
        run: bundle exec fastlane deploy_dev
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          SERVICE_CREDENTIAL_FILE_PATH: gcp_keyfile.json
          GOOGLE_CREDENTIAL_FILE_PATH: play_keyfile.json
