name: 릴리즈 태그 만들기
on:
  pull_request:
    branches:
      - main
    types: [ closed ]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: 브랜치 가져오기
        uses: actions/checkout@v2

      - name: 브랜치명 추출하기
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: 버전 정보 추출
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
        id: extract_version_name

      - name: Release 생성
        if: github.event.pull_request.merged == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}